import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { generateSchedule, generateId } from '@/lib/scheduler';
import { Prisma } from '@prisma/client';

// POST: Create tournament with full setup
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      name,
      players,
      isMixed,
      isFixedPairs,
      fixedPairs,
      numCourts,
      numDays,
      scoringType,
      scoringMode,
      maxPoints,
      winBonus,
    } = body;

    // Validate inputs
    if (!players || players.length < 4) {
      return NextResponse.json(
        { error: 'Servono almeno 4 giocatori' },
        { status: 400 }
      );
    }

    if (!numCourts || numCourts < 1) {
      return NextResponse.json(
        { error: 'Serve almeno 1 campo' },
        { status: 400 }
      );
    }

    if (!numDays || numDays < 1) {
      return NextResponse.json(
        { error: 'Serve almeno 1 giornata' },
        { status: 400 }
      );
    }

    // Validate mixed tournament
    if (isMixed) {
      const males = players.filter((p: { gender: string }) => p.gender === 'M');
      const females = players.filter((p: { gender: string }) => p.gender === 'F');
      if (males.length < 2 || females.length < 2) {
        return NextResponse.json(
          { error: 'Per un torneo misto servono almeno 2 maschi e 2 femmine' },
          { status: 400 }
        );
      }
    }

    // Delete existing tournament if any
    await db.match.deleteMany({});
    await db.setResult.deleteMany({});
    await db.pair.deleteMany({});
    await db.player.deleteMany({});
    await db.tournament.deleteMany({});

    // Create tournament
    const tournament = await db.tournament.create({
      data: {
        name: name || 'Torneo di Padel Americano',
        isMixed: !!isMixed,
        isFixedPairs: !!isFixedPairs,
        numCourts,
        numDays,
        scoringType: scoringType || 'SETS',
        scoringMode: scoringMode || 'BEST_OF_1',
        maxPoints: maxPoints || 18,
        winBonus: winBonus || 2,
      },
    });

    // Create players with IDs
    const playerRecords = await Promise.all(
      players.map((p: { name: string; gender: string }) =>
        db.player.create({
          data: {
            id: generateId(),
            name: p.name,
            gender: p.gender,
            tournamentId: tournament.id,
          },
        })
      )
    );

    const playerData = playerRecords.map(p => ({
      id: p.id,
      name: p.name,
      gender: p.gender as 'M' | 'F',
    }));

    // Handle fixed pairs
    let fixedPairData: { id: string; player1Id: string; player2Id: string; player1Name: string; player2Name: string; isFixed: boolean }[] = [];

    if (isFixedPairs && fixedPairs && fixedPairs.length > 0) {
      // fixedPairs is array of { player1Index, player2Index } (0-based indices into players array)
      fixedPairData = fixedPairs.map((fp: { player1Index: number; player2Index: number }) => ({
        id: generateId(),
        player1Id: playerData[fp.player1Index].id,
        player2Id: playerData[fp.player2Index].id,
        player1Name: playerData[fp.player1Index].name,
        player2Name: playerData[fp.player2Index].name,
        isFixed: true,
      }));

      await Promise.all(
        fixedPairData.map(fp =>
          db.pair.create({
            data: {
              id: fp.id,
              player1Id: fp.player1Id,
              player2Id: fp.player2Id,
              player1Name: fp.player1Name,
              player2Name: fp.player2Name,
              tournamentId: tournament.id,
              isFixed: true,
            },
          })
        )
      );
    }

    // Generate schedule
    const schedule = generateSchedule({
      players: playerData,
      isMixed: !!isMixed,
      isFixedPairs: !!isFixedPairs,
      fixedPairs: fixedPairData,
      numCourts,
      numDays,
    });

    // Create pairs for mobile pairs (they're generated by the scheduler)
    if (!isFixedPairs && schedule.pairs.length > 0) {
      await Promise.all(
        schedule.pairs.map(fp =>
          db.pair.create({
            data: {
              id: fp.id,
              player1Id: fp.player1Id,
              player2Id: fp.player2Id,
              player1Name: fp.player1Name,
              player2Name: fp.player2Name,
              tournamentId: tournament.id,
              isFixed: false,
            },
          })
        )
      );
    }

    // Create matches
    if (schedule.matches.length > 0) {
      await Promise.all(
        schedule.matches.map(m =>
          db.match.create({
            data: {
              id: generateId(),
              tournamentId: tournament.id,
              dayNumber: m.dayNumber,
              courtNumber: m.courtNumber,
              team1Id: m.team1.id,
              team2Id: m.team2.id,
              status: 'SCHEDULED',
            },
          })
        )
      );
    }

    return NextResponse.json({
      success: true,
      tournamentId: tournament.id,
      message: 'Torneo creato con successo!',
    });
  } catch (error) {
    console.error('Error creating tournament:', error);
    return NextResponse.json(
      { error: 'Errore nella creazione del torneo' },
      { status: 500 }
    );
  }
}

// GET: Fetch current tournament with all data
export async function GET() {
  try {
    const tournament = await db.tournament.findFirst({
      include: {
        players: true,
        pairs: true,
        matches: {
          include: {
            setResults: {
              orderBy: { setNumber: 'asc' },
            },
          },
          orderBy: [{ dayNumber: 'asc' }, { courtNumber: 'asc' }],
        },
      },
    });

    if (!tournament) {
      return NextResponse.json({ exists: false });
    }

    return NextResponse.json({ exists: true, tournament });
  } catch (error) {
    console.error('Error fetching tournament:', error);
    return NextResponse.json(
      { error: 'Errore nel caricamento del torneo' },
      { status: 500 }
    );
  }
}
